---
abstract: 'Perl extension for basic validation of'
author:
  - 'collin seaton <cseaton@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Validate-VIN
provides:
  Data::Validate::VIN:
    file: lib/Data/Validate/VIN.pm
    version: '0.04'
requires:
  perl: '5.008'
resources:
  license: http://dev.perl.org/licenses/
version: '0.04'
